version: "3"
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "root"

    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

    networks:
      khalil:
        ipv4_address: "10.56.1.20"
  web:
    image: wordpress
    ports:
      - "8080:80"

    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "root"
      WORDPRESS_DB_NAME: wordpress

    depends_on:
      - database
    restart: always

    networks:
      khalil:
        ipv4_address: "10.56.1.21"

  mongodb:
    container_name: mongodb
    build: ./docker
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

    networks:
      khalil:
        ipv4_address: "10.56.1.23"


networks:
  khalil:
    ipam:
      driver: default
      config:
        - subnet: "10.56.1.0/24"
